spring.application.name=ai-banking-agent

## H2 config
spring.datasource.url=jdbc:h2:file:./data/bankdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
#
## Enable H2 console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Ensure schema.sql is executed on startup
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:data.sql
#spring.sql.init.data-locations=classpath:data.sql

#spring.ai.openai.api-key=
#spring.ai.openai.base-url=https://api.openai.com/v1  # optional, defaults to OpenAI's endpoint